ROM python:3.11-slim-bullseye

ENV TZ=Europe/Moscow

RUN mkdir -p /home/app

RUN addgroup --system app && adduser --system --group app

ENV HOME=/home/app

ENV APP_HOME=/home/app/web

RUN mkdir $APP_HOME

WORKDIR $APP_HOME

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY app $APP_HOME

RUN chown -R app:app $APP_HOME

USER app
