---
version: "3.7"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    restart: unless-stopped
    entrypoint: [ "gunicorn", "-w", "2", "--bind", "0.0.0.0:5000", "main:app" ]
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    env_file:
      - .env
    healthcheck:
      test: mysql $MYSQL_DATABASE -u $MYSQL_USER --password=$MYSQL_PASSWORD -e 'SELECT 1;'
      interval: 3s
      timeout: 2s
      retries: 2
      start_period: 2s
    restart: unless-stopped
    logging:
      options:
        max-size: "500M"
        max-file: "2"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}
