FROM python:3.11-slim-bullseye

ENV TZ=Europe/Moscow

RUN useradd uwsgi -m -s /bin/bash

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

USER uwsgi

COPY app ./
