---
version: "3.7"

services:

  app:
    image: python:google
    build:
      context: .
      dockerfile: Dockerfile
    container_name: byte-app
    # restart: unless-stopped
    env_file:
      - db.env
    depends_on: 
      backend:
        condition: service_healthy
#    volumes:
#      - /home/tech/Project/content:/usr/share/nginx/html
#    networks:
#      - nginx_default

  backend:
    image: mysql:8
    container_name: byte-mysql
    env_file:
      - db.env
    healthcheck:
      test: mysql bytedb -u byter --password=bytepass -e 'SELECT 1;'
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    logging:
      options:
        max-size: "500M"
        max-file: "2"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
#    networks:
#      - nginx_default

networks:
  nginx_default:
    external: true
 
volumes:
  db: {}
