import os

MYSQL_HOST = os.getenv('MYSQL_HOST')
MYSQL_PORT = os.getenv('MYSQL_PORT')
MYSQL_DB = os.getenv('MYSQL_DATABASE')
MYSQL_USER = os.getenv('MYSQL_USER')
MYSQL_PASS = os.getenv('MYSQL_PASSWORD')

GOOGLE_FILE_ID = os.getenv('GOOGLE_FILE_ID')
GOOGLE_URL_CSV = os.getenv('GOOGLE_URL_CSV')

HEADERS_USER_AGENT = os.getenv('HEADERS_USER_AGENT')
HEADERS_DNT = os.getenv('HEADERS_DNT')
HEADERS_ACCEPT = os.getenv('HEADERS_ACCEPT')
HEADERS_ACCEPT_CHARSET = os.getenv('HEADERS_ACCEPT_CHARSET')
HEADERS_ACCEPT_ENCODING = os.getenv('HEADERS_ACCEPT_ENCODING')
HEADERS_ACCEPT_LANGUAGE = os.getenv('HEADERS_ACCEPT_LANGUAGE')

