{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parsing-sheets.fullname" . }}
  labels:
    {{- include "parsing-sheets.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret | nindent 4 }}
{{- end }}