secret:
  MYSQL_ROOT_PASSWORD: "secret"
  MYSQL_DATABASE: "bytedb"
  MYSQL_USER: "byter"
  MYSQL_PASSWORD: "bytepass"
  MYSQL_HOST: "parsing-sheets-db"
  MYSQL_PORT: "3306"
  LANG: "C.UTF-8"
  GOOGLE_FILE_ID: "1psvvO5eftQYu4ktZ9g8pc70Owy_NPTPGdeuXvt363_0"
  GOOGLE_URL_CSV: "https://docs.google.com/spreadsheets/d/{0}/export?format=csv"

service:
  typeApp: ClusterIP
  typeProxy: ClusterIP
  port: "5000"
  portDb: "3306"
  portProxy: "80"
  nodePort: ""

ingress:
  enabled: true
  className: system-ingress
  annotations:
    cert-manager.io/cluster-issuer: dev-ca-issuer
    cert-manager.io/common-name: app.prokop.local
    cert-manager.io/subject-organizations: "home dev lab"
    cert-manager.io/subject-countries: "RU"
    cert-manager.io/subject-localities: "Moscow"
    cert-manager.io/duration: "9125h"
    cert-manager.io/renew-before: "360h"
    cert-manager.io/usages: "server auth"
    cert-manager.io/private-key-algorithm: RSA
    cert-manager.io/private-key-encoding: "PKCS8"
    cert-manager.io/private-key-size: "4096"
    cert-manager.io/private-key-rotation-policy: Always
  hosts:
    - host: app.prokop.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: app-tls
      hosts:
        - app.prokop.local

app:
  name: app
  autoscaling:
    enabled: false
    minReplicas: "1"
    maxReplicas: "10"
    targetCPUUtilizationPercentage: "80"
    targetMemoryUtilizationPercentage: "80"
  replicaCount: "1"
  revisionHistoryLimit: "2"
  image:
    repository: registry.prokop.local
    project: pet/parsing-sheets
    name: parsing-sheets-app
    tag: latest
    imagePullPolicy: Always
  command:
      - "gunicorn"
      - "-w"
      - "1"
      - "--bind"
      - "0.0.0.0:5000"
      - "main:app"
  port: "5000"
  livenessProbe:
    httpGet:
      path: /
      port: app-port
  readinessProbe:
    httpGet:
      path: /
      port: app-port
  resources:
    limits:
      cpu: "0.3"
      memory: "256Mi"
    requests:
      cpu: "0.3"
      memory: "256Mi"

db:
# Встроенная база данных mysql, для внешней false
  builtin: true
  name: db
  replicaCount: "1"
  revisionHistoryLimit: "2"
  minReadySeconds: "1"
  terminationGracePeriodSeconds: "1"
  image:
    repository: registry.prokop.local
    project: pet/parsing-sheets
    name: parsing-sheets-db
    tag: latest
    imagePullPolicy: IfNotPresent
  port: "3306"
  resources: {}
    # limits:
    #   cpu: "0.3"
    #   memory: "512Mi"
    # requests:
    #   cpu: "0.2"
    #   memory: "256Mi"
  storage:
    name: data
    mountPath: /var/lib/mysql
    size: "1Gi"
    accessModes: [ "ReadWriteOnce" ]

proxy:
# Активация внутреннего прокси nginx
  builtin: true
  name: proxy
  autoscaling:
    enabled: false
    minReplicas: "1"
    maxReplicas: "10"
    targetCPUUtilizationPercentage: "80"
    targetMemoryUtilizationPercentage: "80"
  replicaCount: "1"
  revisionHistoryLimit: "1"
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
  image:
    repository: ""
    project: ""
    name: nginx
    tag: latest
    imagePullPolicy: IfNotPresent
  port: "8080"
  livenessProbe:
    httpGet:
      path: /
      port: proxy-port
  readinessProbe:
    httpGet:
      path: /
      port: proxy-port
  resources: {}
    # limits:
    #   cpu: "0.3"
    #   memory: "512Mi"
    # requests:
    #   cpu: "0.2"
    #   memory: "256Mi"
  volumes:
    - name: cache
      emptyDir: {}
    - name: run
      emptyDir:
        medium: Memory
    - name: proxy-default-conf
      configMap:
        name: parsing-sheets-proxy
        items:
          - key: default.conf
            path: default.conf
    - name: proxy-nginx-conf
      configMap:
        name: parsing-sheets-proxy
        items:
          - key: nginx.conf
            path: nginx.conf
  volumeMounts:
    - name: cache
      mountPath: /var/cache/
    - name: run
      mountPath: /run
    - name: proxy-default-conf
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
    - name: proxy-nginx-conf
      mountPath: /etc/nginx/nginx.conf
      readOnly: true
      subPath: nginx.conf
  initcontainer:
    image:
      name: busybox
      tag: 1.33.0
      imagePullPolicy: IfNotPresent
    command:
      - "sh"
      - "-c"
      - |
        mkdir /var/cache/nginx
        chown 101:101 /var/cache/nginx
        chmod 775 /var/cache/nginx
    volumeMounts:
      - name: cache
        mountPath: /var/cache/

configs:
  nginx:
    default.conf: |
      server {
        listen       8080;
        # listen  [::]:8080;
        server_name  localhost;

        add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Permissions-Policy "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()";
        add_header Referrer-Policy 'strict-origin';
        add_header Content-Security-Policy "default-src 'self' *.datatables.net *.jsdelivr.net *.jquery.com; style-src *.datatables.net *.jsdelivr.net 'self'; frame-ancestors 'self'; frame-src 'self'; script-src *.datatables.net *.jsdelivr.net *.jquery.com 'self'; img-src 'self' data:;";

        location / {
               proxy_pass http://parsing-sheets-app:5000;
               proxy_set_header Host $host;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header X-Forwarded-Proto $scheme;
               proxy_redirect off;
               proxy_set_header X-Real-IP $remote_addr;
        }

        if ($http_user_agent ~ (msnbot|Purebot|Baiduspider|Lipperhey|Mail.Ru|scrapbot|scrapbotBaiduspider|Yandex|DirBuster|libwww|"")) {
                return 403;
            }
      }
    nginx.conf: |
      user  nginx;
      worker_processes  auto;

      error_log  /var/log/nginx/error.log notice;
      pid        /var/run/nginx.pid;


      events {
        worker_connections  1024;
        multi_accept on;
        use                 epoll;
        epoll_events        512;
      }


      http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format nginx_json escape=json
            '{'
            '"time_local":"$time_local",'
            '"http_host":"$http_host",'
            '"request":"$request",'
            '"status": "$status",'
            '"body_bytes_sent":"$body_bytes_sent",'
            '"request_time":"$request_time",'
            '"upstream_response_time":"$upstream_response_time",'
            '"upstream_response_length":"$upstream_response_length",'
            '"upstream_connect_time":"$upstream_connect_time",'
            '"upstream_status":"$upstream_status",'
            '"upstream_addr":"$upstream_addr",'
            '"http_referrer":"$http_referer",'
            '"http_user_agent":"$http_user_agent",'
            '"request_body":"$request_body",'
            '"request_length":"$request_length",'
            '"remote_ip":"$http_x_forwarded_for",'
            '"remote_addr":"$remote_addr",'
            '"request_uri":"$request_uri",'
            '}';

        access_log  /dev/stdout  nginx_json;
        error_log   /dev/stderr  warn; # warn, error crit, alert, and emerg

        server_tokens  off;
        sendfile        on;
        tcp_nopush      on;
        tcp_nodelay     on;
        keepalive_timeout  65;
        types_hash_max_size 2048;
        types_hash_bucket_size 64;
        client_max_body_size   16M;
        server_names_hash_bucket_size 64;

        ##
        # SSL Settings
        ##
        ssl_session_timeout    1d;
        ssl_session_cache      shared:SSL:10m;
        ssl_session_tickets    off;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers   ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers on;
        add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;

        # OCSP Stapling
        ssl_stapling           on;
        ssl_stapling_verify    on;
        resolver               1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 valid=60s;
        resolver_timeout       2s;

        ##
        # Gzip Settings
        ##
        gzip on;
        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        include /etc/nginx/conf.d/*.conf;
      }
